import{a as f,S,i as s}from"./assets/vendor-DXaqCXe3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();f.defaults.baseURL="https://pixabay.com/api/";const p=async(o,t=1)=>{const{data:i}=await f.get("",{params:{key:"49383072-7b2484b2a76b3ff56b3486fe5",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,pet_page:15,page:t}});return{hits:i.hits,totalHits:i.totalHits}},h=document.querySelector(".gallery");document.querySelector(".loader");let v=new S(".gallery a",{captionsData:"alt",captionDelay:250});function m(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function q(){h.innerHTML=""}function y(o){const t=o.map(({webformatURL:i,largeImageURL:d,tags:e,likes:r,views:l,comments:b,downloads:w})=>`
        <li class="gallery-item">
            <a href="${d}">
                <img src="${i}" alt="${e}" loading="lazy">
            </a>
             <ul class="info">
                <li class="description"><span>Likes</span> ${r}</li>
                <li class="description"><span>Views</span> ${l}</li>
                <li class="description"><span>Comments</span> ${b}</li>
                <li class="description"><span>Downloads</span> ${w}</li>
             </ul>
        </li>`).join("");h.insertAdjacentHTML("beforeend",t),v.refresh()}const L=document.querySelector(".form"),E=L.querySelector("input"),n=document.querySelector(".btn-load");let c="",a=1,u=0;n.classList.add("hidden");L.addEventListener("submit",async o=>{if(o.preventDefault(),c=E.value.trim(),!c){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}a=1,u=0,q(),n.classList.add("hidden"),m();try{const{hits:t,totalHits:i}=await p(c,a);if(u=i,t.length===0){s.error({title:"Error",message:`Sorry, no images found for "${c}".`,position:"topRight"});return}y(t),a*15<u?n.classList.remove("hidden"):s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){s.error({title:"Error",message:"Oops! Something went wrong. Try again later.",position:"topRight"}),console.error("Error fetching images:",t)}finally{g()}});n.addEventListener("click",async()=>{a++,m(),n.classList.add("hidden");try{const{hits:o}=await p(c,a);y(o),H(),a*15>=u?s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):n.classList.remove("hidden")}catch(o){s.error({title:"Error",message:"Oops! Something went wrong. Try again later.",position:"topRight"}),console.error("Error fetching images:",o)}finally{g()}});function H(){var t;const o=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect().height)||150;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
