import{a as f,S,i as n}from"./assets/vendor-DXaqCXe3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();f.defaults.baseURL="https://pixabay.com/api/";const h=async(i,t=1)=>{const{data:o}=await f.get("",{params:{key:"49383072-7b2484b2a76b3ff56b3486fe5",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,pet_page:15,page:t}});return{hits:o.hits,totalHits:o.totalHits}},p=document.querySelector(".gallery");document.querySelector(".loader");let q=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(){document.querySelector(".loader").classList.remove("hidden")}function m(){document.querySelector(".loader").classList.add("hidden")}function v(){p.innerHTML=""}function y(i){const t=i.map(({webformatURL:o,largeImageURL:c,tags:e,likes:r,views:a,comments:b,downloads:w})=>`
        <li class="gallery-item">
            <a href="${c}">
                <img src="${o}" alt="${e}" loading="lazy">
            </a>
             <ul class="info">
                <li class="description"><span>Likes</span> ${r}</li>
                <li class="description"><span>Views</span> ${a}</li>
                <li class="description"><span>Comments</span> ${b}</li>
                <li class="description"><span>Downloads</span> ${w}</li>
             </ul>
        </li>`).join("");p.insertAdjacentHTML("beforeend",t),q.refresh()}const L=document.querySelector(".form"),H=L.querySelector("input"),s=document.querySelector(".btn-load");let d="",l=1,u=0;s.classList.add("hidden");L.addEventListener("submit",async i=>{if(i.preventDefault(),d=H.value.trim(),!d){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}l=1,v(),s.classList.add("hidden"),g();try{const{hits:t,totalHits:o}=await h(d,l);if(u=o,t.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t),u>15&&s.classList.remove("hidden")}catch(t){n.error({title:"Error",message:"Oops! Something went wrong. Please try again later.",position:"topRight"}),console.error("Error fetching images:",t)}finally{m()}});s.addEventListener("click",async()=>{l++,g();try{const{hits:i}=await h(d,l);if(i.length===0){s.classList.add("hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}y(i);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:listHeightHeight*2,behavior:"smooth"}),l*15>=u&&(s.classList.add("hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{}finally{m()}});
//# sourceMappingURL=index.js.map
